[project]
name = "reportifyr-examples"
r_version = "4.5"

repositories = [
    {alias = "PRISM", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2026-01-29/"},
]

dependencies = [
    { name = "reportifyr", git = "https://github.com/A2-ai/reportifyr", branch = "dev"},
]
